name: NR Broker intention close action
description: Closes an intention opened in a previous action
branding:
  icon: package
  color: blue

inputs:
  intention_token:
    description: The intention to close
    required: true
  broker_url:
    default: https://broker.io.nrs.gov.bc.ca
    description: The broker url.
  outcome:
    default: success
    description: The outcome of the intention. Must be 'success', 'failure' or 'unknown'
  reason:
    default:
    description: The reason for the intention close.

outputs:
  audit_url:
    description: The audit url
    value: ${{ steps.broker-intention-close.outputs.audit-url }}

runs:
  using: "composite"
  steps:
    - shell: bash
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    - id: broker-intention-close
      shell: bash
      env:
        BROKER_URL: ${{ inputs.broker_url }}
        INTENTION_TOKEN: ${{ inputs.intention_token }}
        OUTCOME: ${{ inputs.outcome }}
        REASON: ${{ inputs.reason }}
      run: intention-close.sh


